import { execFileSync } from 'child_process';

/**
 * Read-only helpers for peering at the database the funnel just wrote to.
 *
 * Credential handling is the whole point of this file. PGPASSWORD travels in
 * the child's environment and never appears in argv; psql is invoked argument
 * by argument so no shell quoting or interpolation is involved; and a failed
 * query is reported as a bare "query failed" rather than the executed command,
 * whose text would carry the connection string into a CI log.
 *
 * Contact details never appear in these queries' output or in any message that
 * could reach a log. Lead ids are UUIDs generated by the tests themselves, so
 * interpolating them into the SQL text is safe — there is no user-supplied
 * input here.
 */

const CONN = process.env.DATABASE_URL?.trim() ?? '';
const PGPASS = process.env.PGPASSWORD ?? '';
const HAS_DB = Boolean(CONN && PGPASS);

function psqlArgs(query: string): string[] {
  const url = new URL(CONN);
  const db = url.pathname === '' || url.pathname === '/' ? 'postgres' : url.pathname.replace(/^\//, '');
  return [
    '-tA',
    '-X',
    '-h',
    url.hostname,
    '-p',
    url.port || '5432',
    '-U',
    url.username,
    '-d',
    db,
    '-c',
    query,
  ];
}

export function hasDb(): boolean {
  return HAS_DB;
}

export function dbQueryText(query: string): string {
  if (!HAS_DB) return '';
  try {
    return execFileSync('psql', psqlArgs(query), {
      encoding: 'utf-8',
      timeout: 30_000,
      env: { ...process.env, PGPASSWORD: PGPASS },
    }).trim();
  } catch {
    // Never log the error: its message can embed the executed command line
    // and, through it, the connection string.
    return '';
  }
}

export function dbQueryJson(query: string): unknown {
  const text = dbQueryText(query);
  if (text === '') return null;
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

/**
 * Wait until EVERY outbox row for this lead has reached a terminal state.
 *
 * An earlier version waited on `pending == 0`, which is the false confidence
 * this exists to kill: a delivered Meta event can leave the lead with a
 * `failed` row for Airtable still mid-backoff, and that check would pass a
 * lead that is nowhere near settled.
 */
export async function waitForSettled(leadId: string, maxWaitMs = 20_000): Promise<boolean> {
  const deadline = Date.now() + maxWaitMs;
  for (;;) {
    const unsettled = dbQueryText(
      `select count(*) from delivery_outbox
         where lead_id = '${leadId}' and status in ('pending', 'failed', 'delivering')`
    );
    if (unsettled === '0') return true;
    if (Date.now() >= deadline) return false;
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
}

export function deliveryStatus(leadId: string, destination: string): string | null {
  const value = dbQueryText(
    `select status from delivery_outbox
       where lead_id = '${leadId}' and destination = '${destination}'`
  );
  return value === '' ? null : value;
}

/**
 * Count outbox rows by status across a set of lead ids — the test cohort.
 *
 * Scope is deliberate: the store is shared with the live funnel, so a global
 * "zero pending" assertion would fail an unrelated production row and prove
 * nothing about the runs that just happened. This only ever counts the leads
 * these tests created.
 */
export function countCohort(leadIds: string[], statuses: string[]): number {
  if (leadIds.length === 0) return 0;
  const ids = leadIds.map((id) => `'${id}'`).join(',');
  const states = statuses.map((s) => `'${s}'`).join(',');
  const text = dbQueryText(
    `select count(*) from delivery_outbox
       where lead_id in (${ids}) and status in (${states})`
  );
  return Number.parseInt(text, 10) || 0;
}